seed: 233

model:
  name: DistMult
  embedding_dim: 350
  regularizer: LpRegularizer
  regularizer_kwargs:
    p: 3.0
    weight: 1.0e-4

train:
  batch_count: 100
  lr: 1.0e-4
  loss: multiclass_nll
  eta: 50
  epochs: 4000

eval:
  batch_size: 10000
  ranking_strategy: worst
  
